# Generated by Django 4.2.4 on 2023-08-09 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='pes_enreco',
            new_name='pes_endereco',
        ),
        migrations.RenameField(
            model_name='pessoa_juridica',
            old_name='pjuri_enreco',
            new_name='pjuri_endereco',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pes_usuario_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoa_juridica',
            name='pjuri_usuario_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pes_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
