# Generated by Django 4.2.4 on 2023-08-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_pes_enreco_pessoa_pes_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='pes_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
